#!/usr/bin/env php
<?php
set_error_handler(function($errno, $errstr, $errfile, $errline){
    throw new ErrorException($errstr, $errno, 0, $errfile, $errline);
});

require "vendor/autoload.php";

$config = (isset($argv[1])) ? require($argv[1]) : ['screen_name_list'=>['sugamasao']];

foreach($config['screen_name_list'] as $screen_name){
    try{
        $post = \Uzulla\Pplog\Crawl::get($screen_name);
    }catch(\Exception $e){
        echo "error at {$screen_name} > cause:".$e->getMessage()."\n";
        continue;
    }

    echo "{$post->created_at->format('Y/m/d H:i:s')} {$post->screen_name} > {$post->title}\n{$post->text}\n";

    if(!empty($post->comment_list)){
        foreach($post->comment_list as $comment){
            echo " +>{$comment->screen_name}>{$comment->text}\n";
        }
    }
    echo "==============================================================\n";
}
